Insights Scripts
connectall/valueops-jenkins-pipeline-library pull request #1
Opened 2024-07-29 22:58 UTC by wbeard

Just opening a draft as a check-in point before we meet! 

So far, just authored them as bash scripts so I could run them locally. So, before merging, I'm assuming we'll need to refactor into groovy scripts executing bash.

I tried to keep the bash scripts close to the the connectall versions, so there shouldn't be too many differences. I also added an `updateDeploys` script that we can use to update the success status & time the deploy finished.

2024-07-31 18:00 UTC, sbhaskara-ca requested changes
Add Readme with documentation and a sample Jenkins pipeline as example on the usage of the steps

2024-07-31 18:00 UTC, sbhaskara-ca commented on vars/insights/postCommits.sh
> +_DEPLOY_ID=423575567561
Is this OID for the VSMDeploy? How do you expect to get this?

2024-07-31 18:00 UTC, sbhaskara-ca commented on vars/insights/postDeploys.sh
> +_BUILD_COMPONENT=423575445565
How would we get the Component OID?

2024-07-31 18:00 UTC, sbhaskara-ca commented on vars/insights/postCommits.sh
> +_DEPLOY_ID=423575567561
Why not do the same logic of finding the DeployID based off the current BuildID

2024-07-31 18:00 UTC, sbhaskara-ca commented on vars/postCommitsToInsights.groovy
> +  sh """
@wbeard we do not need to this; we can keep the Shell script as is in the `resources` directory and we can execute it from here. that way its easy to maintain and also testable.

2024-07-31 18:00 UTC, sbhaskara-ca commented on vars/postDeployAndCommitsToInsights.groovy
> +        "DEPLOY_END_TIME=${config.BuildFinishTime}",
Doc to be added about the params and formats

2024-07-31 18:00 UTC, sbhaskara-ca commented on vars/postDeployAndCommitsToInsights.groovy
> +        "GIT_REPO_LOC=${config.GitRepoLoc}",
Ensure if we can handle both relative and absolute paths

2024-07-31 18:00 UTC, sbhaskara-ca commented on vars/postDeployAndCommitsToInsights.groovy
> +        "DEPLOY_IS_SUCCESSFUL=${config.BuildIsSuccessful}",
Call it out as optional

2024-07-31 18:00 UTC, sbhaskara-ca commented on vars/postDeployAndCommitsToInsights.groovy
> +        "DEPLOY_MAIN_REVISION=${config.CurrentBuildCommit}",
Could be Optional -> use Current COMMIT ID if not overridden

2024-07-31 18:00 UTC, sbhaskara-ca commented on resources/postDeployAndCommitsToInsights.sh
> +echo "API_URL: $API_URL"
Example for API URL? What is the format?

2024-07-31 18:00 UTC, sbhaskara-ca commented on resources/updateDeployToInsights.sh
> +        date -r $seconds -u +"%Y-%m-%dT%H:%M:%S%z"
Ensure the timezone is correct, as Rally expects the dates in UTC; we may need to use `Z` instead of `z`

2024-07-31 18:00 UTC, sbhaskara-ca commented on resources/updateDeployToInsights.sh
> +    response=$(curl -s -H "ZSESSIONID: $API_KEY" "$API_URL/vsmdeploy?query=(BuildId%20=%20$build_id)&workspace=workspace/$API_WORKSPACE_OID&fetch=ObjectID")
expect `API_URL` will only be either `https://rally1.rallydev.com` or `https:\\vsi.rallydev.com`

2024-07-31 18:00 UTC, sbhaskara-ca commented on resources/postDeployAndCommitsToInsights.sh
> +
Add some validation on the commit_id as sometimes the repo's that are polled might not have any commits done on a repo.

2024-07-31 21:43 UTC, wbeard commented on resources/updateDeployToInsights.sh
> +        date -r $seconds -u +"%Y-%m-%dT%H:%M:%S%z"
Turns out we can just drop the `Z` entirely. It's read in the workspace's timezone on the way out so just passing this dateTime is enough.

2024-07-31 21:59 UTC, wbeard commented on vars/insights/postDeploys.sh
> +_BUILD_COMPONENT=423575445565
We could switch to use a Component name instead, but would mean that if the component were ever renamed, there would have to be a corresponding change here.

I think when we discussed today, we settled on doing this in another PR which I'm up for if it helps simplify onboarding!

2024-07-31 22:01 UTC, wbeard commented on vars/postDeployAndCommitsToInsights.groovy
> +        "DEPLOY_MAIN_REVISION=${config.CurrentBuildCommit}",
Is there an env var in Jenkins I can default to here if this arg's not passed in? I could do it further down in the script, but figured if a smart default's available in this context, we should do it here to keep the script as simple as possible.

2024-08-01 04:56 UTC, sbhaskara-ca commented
@wbeard this looks good. If you have no more planned changes; I will proceed to merge and tag this.

2024-08-01 14:55 UTC, wbeard commented
> @wbeard this looks good. If you have no more planned changes; I will proceed to merge and tag this.

I made a few changes last night that I'm going to test out in my environment. I'll comment back once I've tested them and the branch is in a stable place!

2024-08-01 15:48 UTC, wbeard commented
@sbhaskara-ca I went ahead and implemented the "lookup component by component name" path we talked about. All appears functional in my testing. I am done with the PR on my end, so feel free to merge!

2024-08-01 17:00 UTC, sbhaskara-ca approved these changes

2024-08-01 17:00 UTC, merged